version: '3'

services:
    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
        container_name: elasticsearch
        restart: always
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=true
            - discovery.type=single-node
            - ELASTIC_PASSWORD=PleaseChangeMe
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
        - "9200:9200"
        expose:
        - "9200"
    kibana:
        image: docker.elastic.co/kibana/kibana:7.3.2
        container_name: kibana
        hostname: kibana
        restart: always
        environment:
        - SERVER_NAME=kibana.localhost
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - XPACK_SECURITY_ENABLED=true
        - ELASTICSEARCH_USERNAME=elastic
        - ELASTICSEARCH_PASSWORD=PleaseChangeMe
        ports:
        - "5601:5601"
        expose:
        - "5601"
        links:
        - elasticsearch
        depends_on:
        - elasticsearch
